/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessDocumentRouteImport } from './routes/api/process-document'
import { Route as ApiAskCopilotRouteImport } from './routes/api/ask-copilot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessDocumentRoute = ApiProcessDocumentRouteImport.update({
  id: '/api/process-document',
  path: '/api/process-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskCopilotRoute = ApiAskCopilotRouteImport.update({
  id: '/api/ask-copilot',
  path: '/api/ask-copilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/ask-copilot': typeof ApiAskCopilotRoute
  '/api/process-document': typeof ApiProcessDocumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/ask-copilot': typeof ApiAskCopilotRoute
  '/api/process-document': typeof ApiProcessDocumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/ask-copilot': typeof ApiAskCopilotRoute
  '/api/process-document': typeof ApiProcessDocumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/api/ask-copilot' | '/api/process-document'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/api/ask-copilot' | '/api/process-document'
  id: '__root__' | '/' | '/auth' | '/api/ask-copilot' | '/api/process-document'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiAskCopilotRoute: typeof ApiAskCopilotRoute
  ApiProcessDocumentRoute: typeof ApiProcessDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-document': {
      id: '/api/process-document'
      path: '/api/process-document'
      fullPath: '/api/process-document'
      preLoaderRoute: typeof ApiProcessDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask-copilot': {
      id: '/api/ask-copilot'
      path: '/api/ask-copilot'
      fullPath: '/api/ask-copilot'
      preLoaderRoute: typeof ApiAskCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiAskCopilotRoute: ApiAskCopilotRoute,
  ApiProcessDocumentRoute: ApiProcessDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
