/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessDocumentRouteImport } from './routes/api/process-document'
import { Route as ApiAskCopilotRouteImport } from './routes/api/ask-copilot'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminDocumentosRouteImport } from './routes/_authenticated/admin.documentos'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessDocumentRoute = ApiProcessDocumentRouteImport.update({
  id: '/api/process-document',
  path: '/api/process-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskCopilotRoute = ApiAskCopilotRouteImport.update({
  id: '/api/ask-copilot',
  path: '/api/ask-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDocumentosRoute =
  AuthenticatedAdminDocumentosRouteImport.update({
    id: '/admin/documentos',
    path: '/admin/documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/governanca': typeof GovernancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/chat': typeof AuthenticatedChatRoute
  '/api/ask-copilot': typeof ApiAskCopilotRoute
  '/api/process-document': typeof ApiProcessDocumentRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/governanca': typeof GovernancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/chat': typeof AuthenticatedChatRoute
  '/api/ask-copilot': typeof ApiAskCopilotRoute
  '/api/process-document': typeof ApiProcessDocumentRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/governanca': typeof GovernancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/api/ask-copilot': typeof ApiAskCopilotRoute
  '/api/process-document': typeof ApiProcessDocumentRoute
  '/_authenticated/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/governanca'
    | '/sitemap.xml'
    | '/sobre'
    | '/chat'
    | '/api/ask-copilot'
    | '/api/process-document'
    | '/admin/documentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/governanca'
    | '/sitemap.xml'
    | '/sobre'
    | '/chat'
    | '/api/ask-copilot'
    | '/api/process-document'
    | '/admin/documentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/governanca'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/chat'
    | '/api/ask-copilot'
    | '/api/process-document'
    | '/_authenticated/admin/documentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GovernancaRoute: typeof GovernancaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ApiAskCopilotRoute: typeof ApiAskCopilotRoute
  ApiProcessDocumentRoute: typeof ApiProcessDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-document': {
      id: '/api/process-document'
      path: '/api/process-document'
      fullPath: '/api/process-document'
      preLoaderRoute: typeof ApiProcessDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask-copilot': {
      id: '/api/ask-copilot'
      path: '/api/ask-copilot'
      fullPath: '/api/ask-copilot'
      preLoaderRoute: typeof ApiAskCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/documentos': {
      id: '/_authenticated/admin/documentos'
      path: '/admin/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AuthenticatedAdminDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedAdminDocumentosRoute: typeof AuthenticatedAdminDocumentosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedAdminDocumentosRoute: AuthenticatedAdminDocumentosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GovernancaRoute: GovernancaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ApiAskCopilotRoute: ApiAskCopilotRoute,
  ApiProcessDocumentRoute: ApiProcessDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
